
- include_vars: "group_vars/github.yml"

- name: Pull app from git
  git: repo={{ code_repository_url }}
       dest={{ repo_dir }}
       version={{ branch_name }}
       force=yes
  notify:
    - reload supervisor
    - install requirements
    - collectstatic
    - migrate db
  tags: git

- name: Create static directory
  file:
    path: "{{ static_dir }}/{{ }}"
    state: directory

- name: Create media directory
  file:
    path: "{{ media_dir }}/{{ media_relative_path }}"
    state: directory
